/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExpeerlyComponent {
        "accentColor": string;
        "gtin": string;
        "maxVideos": number;
        "storeId": string;
        "theme": string;
        "type": 'badge' | 'reviewblock' | 'carousel';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLExpeerlyComponentElement extends Components.ExpeerlyComponent, HTMLStencilElement {
    }
    var HTMLExpeerlyComponentElement: {
        prototype: HTMLExpeerlyComponentElement;
        new (): HTMLExpeerlyComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "expeerly-component": HTMLExpeerlyComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ExpeerlyComponent {
        "accentColor"?: string;
        "gtin"?: string;
        "maxVideos"?: number;
        "storeId"?: string;
        "theme"?: string;
        "type"?: 'badge' | 'reviewblock' | 'carousel';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "expeerly-component": ExpeerlyComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "expeerly-component": LocalJSX.ExpeerlyComponent & JSXBase.HTMLAttributes<HTMLExpeerlyComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
